@extends('master')
@section('contenido')
  	   <div class="login">
          <div class="wrap">
				<ul class="breadcrumb breadcrumb__t"></ul>
				    <div class="cont span_2_of_about">
				       <h3>Condiciones de servicio</h3>
					   	<p>TENGA EN CUENTA: LA SECCIÓN DE ESTOS TÉRMINOS DE USO DERECHO A LA "RESOLUCIÓN DE DISPUTAS" CONTIENE UNA CLÁUSULA DE ARBITRAJE QUE REQUIERE QUE LAS LITIGIOS SE ARBITREN EN UNA BASE INDIVIDUAL Y PROHIBA RECLAMACIONES DE ACCION DE CLASE. AFECTA CÓMO SE RESUELVE CONFLICTOS ENTRE USTED Y DESEO. ACEPTANDO ESTOS TÉRMINOS DE USO, USTED ACEPTA ESTAR OBLIGADO POR ESTA DISPOSICIÓN DE ARBITRAJE. POR FAVOR, LEA CUIDADOSAMENTE.</p>
					   	<p>TENGA EN CUENTA QUE SU USO Y ACCESO A NUESTROS SERVICIOS (DEFINIDOS A CONTINUACIÓN) ESTÁ SUJETO A LOS SIGUIENTES TÉRMINOS; SI USTED NO ACEPTA TODOS LOS SIGUIENTES, USTED NO PUEDE USAR NI ACCEDER A LOS SERVICIOS DE NINGUNA MANERA.</p>
					   	<p>Términos de Uso</p>
					   	<p>Fecha de vigencia: 15 de julio de 2018</p>
					   	<p>Siga leyendo para conocer las reglas y restricciones que rigen el uso de nuestros sitios web, productos, servicios y aplicaciones (los "Servicios"). Si tiene alguna pregunta, comentario o preocupación con respecto a estos términos o los Servicios.</p>
					   	<p>Estos Términos de Uso (los "Términos") son un contrato vinculante entre usted y ContextLogic, Inc. ("Deseo", "nosotros" y "nosotros"). Usted debe aceptar y aceptar todos los Términos, o no tiene derecho a utilizar los Servicios. Su uso de los Servicios de cualquier manera significa que usted está de acuerdo con todos estos Términos, y estos Términos permanecerán en vigor mientras usted usa los Servicios. Estos Términos incluyen las disposiciones de este documento, así como las de la Política de Privacidad y la Política de Disputas de Derechos de Autor.</p>
					   	<p>¿Cambiarán estos Términos?</p>
					   	<p>Estamos constantemente tratando de mejorar nuestros Servicios, por lo que estos Términos pueden necesitar cambiar junto con los Servicios. Nos reservamos el derecho de cambiar los Términos en cualquier momento, pero si lo hacemos, lo traeremos a su atención poniendo un aviso en los Servicios, enviándote un correo electrónico, y / o por otros medios. Si no está de acuerdo con los nuevos Términos, puede rechazarlos; Desafortunadamente, eso significa que ya no podrá utilizar los Servicios. Si utiliza los Servicios de cualquier manera después de que un cambio a los Términos es efectivo, significa que acepta todos los cambios.</p>
					   	<p>A excepción de los cambios por nosotros descritos aquí, ninguna otra enmienda o modificación de estos Términos será efectiva a menos que por escrito y firmado por usted y nosotros.</p>
					   	<p>¿Qué pasa con mi privacidad?</p>
					   	<p>Lunettes toma muy en serio la privacidad de sus usuarios. Para conocer la Política de privacidad actual, visite aquí.</p>
					   	<p>La Ley de Protección de la Privacidad de los Niños en Internet ("COPPA") requiere que los proveedores de servicios en línea obtengan el consentimiento de los padres antes de recopilar conscientemente información de identificación personal en línea de niños menores de 13 años. Si usted es un niño menor de 13 años, por favor no intente registrarse para los Servicios o enviar cualquier información personal sobre usted a nosotros. Los padres y tutores legales no pueden aceptar estos Términos o registrarse para los Servicios en nombre de niños menores de 13 años. Si nos enteramos de que hemos recolectado información personal de un niño menor de 13 años, lo borraremos tan pronto como sea posible. Si usted cree que un niño menor de 13 años nos puede haber proporcionado información personal, por favor contáctenos a privacy@contextLogic.com</p>
					   	<p>¿Cuáles son los aspectos básicos del uso de los Servicios?</p>
					   	<p>Es posible que deba registrarse para obtener una cuenta y seleccionar una contraseña y un nombre de usuario ("Identificación de usuario deseada"). Usted se compromete a proporcionarnos información de registro exacta, completa y actualizada sobre usted. No puede seleccionar como ID de usuario de su deseo un nombre que no tiene el derecho de usar o el nombre de otra persona con la intención de hacerse pasar por esa persona. Usted no puede transferir su cuenta a otra persona sin nuestro previo permiso por escrito.</p>
					   	<p>Usted declara y garantiza que es un individuo mayor de edad para formar un contrato vinculante (o si no, ha recibido el permiso de sus padres o tutores para usar los Servicios y hacer que sus padres o tutores acepten estos Términos en su nombre).</p>
					   	<p>Solo utilizará los Servicios para su uso interno, personal, de uso y no en nombre de terceros o para beneficio de terceros, y solo de una manera que cumpla con todas las leyes que se apliquen a usted. Si su uso de los Servicios está prohibido por cualquier ley aplicable, entonces usted no está autorizado a utilizar los Servicios. No podemos y no seremos responsables de su uso de los Servicios de una manera que viola la ley.</p>
					   	<p>No compartirá su cuenta o contraseña con nadie y deberá proteger la seguridad de su cuenta y su contraseña. Usted es responsable de cualquier actividad asociada con su cuenta.</p>
					   	<p>Es posible que tenga varias cuentas en Lunettes pero Lunettes prohíbe estrictamente el uso de varias cuentas para el mismo usuario único o el uso de una cuenta para varios usuarios con el fin de ganar más recompensas. Lunettes no honrará las recompensas obtenidas de tales cuentas.</p>
					   	<p>Al utilizar los Servicios, automáticamente se considerará que ha optado por recibir una comunicación por correo electrónico de parte nuestra. Cuando inicie sesión por primera vez, sus preferencias se establecerán para publicar automáticamente todas las interacciones sociales en otras redes sociales. Sin embargo, podrá editar estas preferencias en cualquier momento en "Configuración".</p>
					   	<p>Su uso de los Servicios está sujeto a las siguientes restricciones adicionales:</p>
					   	<p>Usted declara, garantiza y acepta que no contribuirá con ningún Contenido o Presentación de Usuario (cada uno de esos términos se define a continuación) o de otra manera utilizar los Servicios o interactuar con los Servicios de una manera que:</p>
					   	<p>A: Inflinge o viole los derechos de propiedad intelectual o cualquier otro derecho de cualquier otra persona (incluido Lunettes).</p>
					   	<p>B: Violar cualquier ley o regulación, incluyendo cualquier ley de control de exportación aplicable.</p>
					   	<p>C: Es dañino, fraudulento, engañoso, amenazante, acosador, difamatorio, obsceno o de cualquier otra manera objetable.</p>
					   	<p>D: Poner en peligro la seguridad de tu cuenta de Wish o de cualquier otra persona (como permitir que otra persona ingrese a los Servicios como tú).</p>
					   	<p>E: Intenta, de cualquier manera, obtener la contraseña, cuenta u otra información de seguridad de cualquier otro usuario.</p>
					   	<p>F: Violar la seguridad de cualquier red informática, o craquea cualquier contraseña o código de cifrado de seguridad.</p>
					   	<p>G: Copia o almacena cualquier porción significativa del Contenido.</p>
					   	<p>H: Decompiles, ingenieros inversos, o de otra manera intenta obtener el código fuente o las ideas subyacentes o la información de los Servicios o relacionados con ello.</p>
					   	<p>I: Cargar, transmitir, distribuir, almacenar, crear, o de cualquier otra manera vender o ofrecer a la venta cualquier artículo prohibido.</p>
					   	<p>Una violación de cualquiera de los anteriores es motivo para la terminación de su derecho de usar o acceder a los Servicios.</p>
					   	<p>¿Cuáles son mis derechos en los Servicios?</p>
					   	<p>Los materiales exhibidos o realizados o disponibles en o a través de los Servicios, incluyendo, pero no limitado a, texto, gráficos, datos, artículos, fotos, imágenes, ilustraciones, Envíos de Usuario y demás (todo lo anterior, ) Están protegidos por derechos de autor y / o otras leyes de propiedad intelectual. Usted se compromete a cumplir con todos los avisos de derechos de autor, reglas de marcas registradas, información y restricciones contenidas en cualquier Contenido al que acceda a través de los Servicios, y no utilizará, copiará, reproducirá, modificará, traducirá, publicará, transmitirá, transmitirá, distribuirá y realizará , Cargar, exhibir, licenciar, vender o explotar de cualquier otra forma cualquier Contenido que no sea de su propiedad, (i) sin el consentimiento previo del propietario de dicho Contenido o (ii) de una manera que viole los derechos de otra persona.</p>
					   	<p>Usted entiende que Lunettes posee los Servicios. Usted no modificará, publicará, transmitirá, participará en la transferencia o venta de, reproducir (excepto lo expresamente previsto en esta Sección), crear obras derivadas basadas en, o explotar de alguna manera cualquiera de los Servicios.</p>
					   	<p>Los Servicios pueden permitirle copiar o descargar ciertos Contenidos; Por favor recuerde que sólo porque esta funcionalidad existe, no significa que todas las restricciones anteriores no se aplican.</p>
					   	<p>¿Tengo que conceder alguna licencia a Wish oa otros usuarios?</p>
					   	<p>Cualquier cosa que publique, cargue, comparta, almacene o proporcione de alguna otra forma a través de los Servicios es su "Presentación de Usuario". Algunos Envíos de Usuario son visibles por otros usuarios. Con el fin de mostrar sus envíos de usuario en los servicios y permitir a otros usuarios disfrutar de ellos (cuando corresponda), nos concede ciertos derechos en dichos envíos de usuario. Tenga en cuenta que todas las siguientes licencias están sujetas a nuestra Política de privacidad en la medida en que se refieren a envíos de usuario que también son su información de identificación personal.</p>
					   	<p>Para todos los Envíos de Usuario, otorga a Lunettes una licencia para traducir, modificar (por motivos técnicos, por ejemplo, asegurarse de que su contenido se puede ver en un iPhone, así como un ordenador) y reproducir y actuar con respecto a tales Envíos de usuario, Cada caso para permitirnos operar los Servicios, como se describe con más detalle a continuación. Se trata de una licencia exclusiva: su propiedad en Envíos de usuario no se ve afectada.</p>
					   	<p>Si almacena un envío de usuario en su cuenta personal de Wish, de una manera que no es visible por ningún otro usuario, excepto usted (una "presentación personal de usuario"), concede a Lunettes la licencia anterior, así como una licencia para mostrar, Realizar y distribuir su Envío de Usuario Personal con el único propósito de hacer que la Presentación de Usuario 
					   	Personal sea accesible para usted y proporcionar los Servicios necesarios para hacerlo.</p>
					   	<p>Si comparte una Presentación de usuario sólo de una manera que sólo ciertos usuarios especificados pueden ver (por ejemplo, un mensaje privado a uno o más usuarios) (una "Petición de usuario limitado para el público"), otorga a Wish las licencias anteriores, como Así como una licencia para exhibir, ejecutar y distribuir su Envío de Usuario Limitado a la Audiencia Limitada con el único propósito de hacer accesible a aquellos Usuarios especificados y proporcionar los Servicios necesarios para que dicha Presentación de Usuario de Audiencia Limitada sea accesible. Además, concede a otros usuarios especificados una licencia para acceder a esa Presentación de Usuario de Audiencia Limitada y para utilizar y ejercer todos los derechos en ella, según lo permita la funcionalidad de los Servicios.</p>
					   	<p>Si comparte públicamente un Envío de Usuario en los Servicios y / o de una manera que no sólo usted o ciertos usuarios especificados puedan ver, o si nos proporciona (en un correo electrónico directo o de otro tipo) comentarios, sugerencias, mejoras, mejoras , Y / o solicitudes de características relacionadas con los Servicios (cada una de las anteriores, una "Submisión de Usuario Público"), otorga a Lunettes las licencias anteriores, así como una licencia para mostrar, realizar y distribuir su Con la finalidad de hacer accesible a todos los usuarios de Wish y de proporcionar los Servicios necesarios para hacerlo, así como todos los demás derechos necesarios para utilizar y ejercer todos los derechos en dicha Presentación de Usuario Público en conexión con los Servicios y / Con el negocio de Wish, siempre que Lunettes intente notificarle si utiliza su Envío de Usuario Público por cualquier motivo que no sea su visualización en los Servicios. Además, concede a todos los demás usuarios de los Servicios una licencia para acceder a dicha Presentación de Usuario Público y para utilizar y ejercer todos los derechos en ella, según lo permita la funcionalidad de los Servicios.</p>
					   	<p>Usted acepta que las licencias que concede son libres de regalías, perpetuas, sublicenciables, irrevocables y en todo el mundo.</p>
					   	<p>Por último, usted entiende y acepta que Lunettes, al realizar los pasos técnicos requeridos para proporcionar los Servicios a nuestros usuarios (incluido usted), puede necesitar hacer cambios en sus Envíos de Usuario para conformar y adaptar dichos User Submissions a los requisitos técnicos de las redes de conexión , Dispositivos, servicios o medios, y las licencias anteriores incluyen los derechos para hacerlo.</p>
						<p>¿Qué pasa si veo algo en los Servicios que infringe mi derecho de autor?</p>
						<p>Es posible que haya oído hablar de la Ley de Derechos de Autor del Milenio Digital (la "DMCA"), ya que se refiere a proveedores de servicios en línea, como Lunettes, pidiéndole que elimine material que supuestamente viola los derechos de autor de alguien. Respetamos los derechos de propiedad intelectual de los demás y nos reservamos el derecho de eliminar o deshabilitar el Contenido alegado que está infringiendo y de cancelar las cuentas de los presuntos infractores; Para revisar nuestra Política de Disputas de Derechos de Autor completa y aprender a reportar contenido potencialmente infractor.</p>
						<p>¿Quién es responsable de lo que veo y hago en los Servicios?</p>
						<p>Cualquier información o contenido publicamente publicado o transmitido en privado a través de los Servicios es responsabilidad exclusiva de la persona de quien se originó dicho contenido y usted accede a dicha información y contenido a su propio riesgo y no somos responsables de ningún error u omisión en Esa información o contenido o por cualquier daño o pérdida que pueda sufrir en relación con él. No podemos controlar y no tenemos el deber de tomar ninguna acción con respecto a cómo usted puede interpretar y utilizar el Contenido o qué acciones puede tomar como resultado de haber estado expuesto al Contenido, y por este medio nos libera de toda responsabilidad por haber adquirido o Contenido no adquirido a través de los Servicios. No podemos garantizar la identidad de ningún usuario con el que interactúes al utilizar los Servicios y no somos responsables de que los usuarios tengan acceso a los Servicios.</p>
						<p>Usted es responsable de todo el Contenido que usted aporte, de cualquier manera, a los Servicios, y usted representa y garantiza que tiene todos los derechos necesarios para hacerlo, de la manera en que lo aporta. Usted mantendrá toda su información de registro exacta y actualizada. Usted es responsable de toda su actividad relacionada con los Servicios.</p>
						<p>Los Servicios pueden contener enlaces o conexiones a sitios web o servicios de terceros que no son propiedad ni están controlados por Wish. Cuando accede a sitios web de terceros o utiliza servicios de terceros, acepta que existen riesgos al hacerlo y que Wish no es responsable de dichos riesgos. Le animamos a que sea consciente cuando abandone los Servicios y lea los términos y condiciones y la política de privacidad de cada sitio web o servicio de terceros que visite o utilice.</p>
						<p>Lunettes no controla y no asume ninguna responsabilidad por el contenido, la exactitud, las políticas de privacidad, las prácticas u opiniones expresadas en sitios web de terceros o por cualquier tercero con el que interactúe a través de los Servicios. Además, Lunettes no podrá ni puede supervisar, verificar, censurar o editar el contenido de ningún sitio o servicio de terceros. Al utilizar los Servicios, usted nos libera de cualquier responsabilidad derivada del uso de cualquier sitio web o servicio de terceros.</p>
						<p>Sus interacciones con organizaciones y / o personas que se encuentren en o a través de los Servicios, incluyendo el pago y entrega de bienes o servicios, y cualquier otro término, condición, garantía o representación asociada con tales transacciones, son exclusivamente entre usted y dichas organizaciones y / o individuos . Usted debe hacer cualquier investigación que considere necesaria o apropiada antes de proceder con cualquier transacción en línea o fuera de línea con cualquiera de estos terceros. Usted acepta que Lunettes no será responsable por cualquier pérdida o daño de cualquier tipo incurrido como resultado de tales transacciones. En particular, y sin limitar lo anterior, usted acepta que Lunettes no facilita (y no asume responsabilidad alguna) cualquier transacción (o pago o reembolso por lo tanto) arreglada a través de Lunettes Local.</p>
						<p>Si hay una disputa entre los participantes en este sitio, o entre los usuarios y cualquier tercero, usted acepta que Wish no tiene ninguna obligación de participar. En el caso de que tenga una disputa con uno o más usuarios, libera a Lunettes, sus funcionarios, empleados, agentes y sucesores de reclamaciones, demandas y daños de cualquier tipo o naturaleza, conocida o desconocida, sospechada o no sospechada, revelada O no revelados, que surjan de, o de cualquier manera, relacionados con dichas disputas y / o nuestros Servicios.</p>
						<p>USTED Y POR LO PRESENTE RENUNCIARÁ A CALIFORNIA CÓDIGO CIVIL SECCIÓN 1542, QUE DICE: "UNA LIBERACIÓN GENERAL NO SE EXTIENDE A RECLAMOS QUE EL CREDIENTE NO SABE O SOSPECHA EXISTIR EN SU MISMO FAVOR EN EL MOMENTO DE EJECUTAR LA LIBERACIÓN, CONOCIDO POR ÉL O POR ELLA DEBE HABER MATERIALMENTE AFECTADO SU ACUERDO CON EL DEUDOR. "</p>
						<p>¿Desea cambiar los servicios?</p>
						<p>Siempre estamos tratando de mejorar los Servicios, para que puedan cambiar con el tiempo. Podemos suspender o interrumpir cualquier parte de los Servicios, o podemos introducir nuevas características o imponer límites a ciertas características o restringir el acceso a partes oa todos los Servicios. Trataremos de darle aviso cuando realicemos un cambio material en los Servicios que pudiera afectarle negativamente, pero esto no siempre es práctico. Del mismo modo, nos reservamos el derecho de eliminar cualquier Contenido de los Servicios en cualquier momento, por cualquier motivo (incluyendo, pero no limitado a, si alguien alega que usted contribuyó ese Contenido en violación de estos Términos), a nuestra discreción y sin previo aviso.</p>
						<p>¿Los servicios cuestan algo?</p>
						<p>Actualmente, es libre de acceder y navegar por Lunettes.com o por cualquier otro servicio. Sin embargo, usted puede optar por comprar productos a través de los Servicios, y usted solo será responsable de pagar el precio de compra de cualquier producto que compre, además de los impuestos y gastos de envío. Lunettes puede limitar o cancelar cantidades de productos comprados, y se reserva el derecho de rechazar cualquier pedido. En caso de que Lunettes deba realizar un cambio en un pedido, intentará notificarlo poniéndose en contacto con la dirección de correo electrónico, la dirección de facturación y / o el número de teléfono proporcionado en el momento en que se hizo el pedido. Los precios están sujetos a cambios en cualquier momento. Debido a jurisdicciones fiscales separadas y aplicables, sus compras pueden estar sujetas a impuestos específicos de ventas, personalizados o de valor agregado, y el tiempo de envío y el costo asociado pueden aumentar en consecuencia.</p>
						<p>Lunettes se reserva el derecho de exigir el pago de los honorarios por ciertos o todos los Servicios, además de los honorarios cobrados por la compra de productos. Usted deberá pagar todos los honorarios, como se describe en el sitio web en relación con los servicios seleccionados por usted. Lunettes se reserva el derecho de cambiar su lista de precios e instituir nuevos cargos en cualquier momento, previa notificación a usted, la cual puede ser enviada por correo electrónico o publicada en el Sitio Web. Su uso de los Servicios después de dicha notificación constituye su aceptación de cualquier cargo nuevo o aumentado.</p>
						<p>¿Qué sucede si debo devolver una compra?</p>
						<p>Usted puede devolver todos los productos dentro de los 30 días de la entrega. Puede iniciar una devolución o un reembolso en artículos de la página Historial de pedidos. Simplemente haga clic en "Contactar con Soporte" al lado del artículo que desea solicitar una devolución o un reembolso y Lunettes Support estará listo para ayudar.</p>
						<p>Nuestro objetivo es procesar todas las solicitudes dentro de las 72 horas siguientes a la recepción. Los reembolsos se devuelven a la forma original de pago usada para comprar la orden. Si tiene alguna pregunta sobre el estado de su reembolso, su declaración o su cuenta, no dude en ponerse en contacto con Wish Support en support@Lunettes.com. </p>
						<p>Si se aplica un crédito promocional Wish a una orden y que la orden se devuelve por cualquier motivo, no se reembolsará ningún crédito promocional utilizado en esa orden.</p>
						<p>Lunettes no puede reembolsar, reembolsar, cubrir, o de otra manera ser responsable de los honorarios no pagados a Wish. Esto incluye cualquier impuesto de aduana o IVA así como cualquier coste de envío de vuelta que usted puede incurrir en el proceso del reembolso.</p>
						<p>Sin embargo, las condiciones de devolución y devolución anteriores NO se aplican a ningún producto que compre utilizando Lunettes Local. Las transacciones realizadas usando Lunettes Local son enteramente entre usted y el otro usuario de Wish Local.</p>
						<p>¿Qué pasa si quiero dejar de usar los Servicios?</p>
						<p>Usted es libre de hacer eso en cualquier momento, siguiendo los pasos aquí. Consulte nuestra Política de privacidad, así como las licencias anteriores, para entender cómo tratamos la información que nos proporciona después de haber dejado de utilizar nuestros servicios. Lunettes también es libre de terminar (o suspender el acceso a) su uso de los Servicios o su cuenta, por cualquier razón a nuestra discreción, incluyendo su incumplimiento de estos Términos. Lunettes tiene el derecho exclusivo de decidir si está violando cualquiera de las restricciones establecidas en estos Términos.</p>
						<p>La cancelación de la cuenta puede resultar en la destrucción de cualquier contenido asociado con su cuenta, por lo que debe tener esto en cuenta antes de decidir cancelar su cuenta.</p>
						<p>Las disposiciones que, por su naturaleza, deberían sobrevivir a la terminación de estos Términos, sobrevivirán a la terminación. A modo de ejemplo, todo lo siguiente sobrevivirá a la rescisión: cualquier obligación que tenga que pagarnos o indemnizarnos, cualquier limitación de nuestra responsabilidad, términos relativos a la propiedad o derechos de propiedad intelectual y términos relativos a disputas entre nosotros.</p>
						<p>¿Qué más necesito saber?</p>
						<p>Renuncia a la garantía. Ni Lunettes ni sus otorgantes de licencias ni proveedores hacen ninguna representación o garantía con respecto a cualquier contenido contenido en o accesado a través de los Servicios y no seremos responsables por la exactitud, conformidad con los derechos de autor, legalidad o decencia del material contenido o accesado a través del Servicios. Nosotros (y nuestros licenciadores y proveedores) no hacemos representaciones ni garantías con respecto a sugerencias o recomendaciones de servicios o productos ofrecidos o comprados a través de los Servicios. Los productos y servicios comprados u ofrecidos (siguiendo o no las recomendaciones y sugerencias) a través de los Servicios se proporcionan "TAL CUAL" y sin ninguna garantía de ningún tipo de Lunettes o de otros (a menos que, con respecto a otros sólo, siempre y expresamente y sin ambigüedad Por escrito por un tercero designado para un producto específico). LOS SERVICIOS Y CONTENIDO SE PROPORCIONAN POR LUNETTES (Y SUS LICENCIATARIOS Y PROVEEDORES) EN UNA BASE "TAL COMO ESTÁ", SIN GARANTÍAS O CUALQUIER TIPO, EXPLÍCITAS O IMPLÍCITAS, INCLUYENDO, SIN LIMITACIÓN, GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD, ADECUACIÓN PARA UN PROPÓSITO PARTICULAR , NO INFRACCIÓN O QUE EL USO DE LOS SERVICIOS SERÁ ININTERRUMPIDO O LIBRE DE ERRORES. ALGUNOS ESTADOS NO PERMITEN LIMITACIONES SOBRE LA DURACIÓN DE UNA GARANTÍA IMPLÍCITA, POR LO QUE LAS LIMITACIONES ANTERIORES PUEDEN NO APLICARSE A USTED.</p>
						<p>Limitación de responsabilidad. BAJO NINGUNA CIRCUNSTANCIA Y BAJO NINGUNA TEORÍA LEGAL (INCLUYENDO, SIN LIMITACIÓN, AGRAVIO, CONTRATO, RESPONSABILIDAD ESTRICTA, O DE OTRA MANERA) DESEA (O SUS LICENCIANTES O PROVEEDORES) SER RESPONSABLE ANTE USTED O CUALQUIER OTRA PERSONA POR (A) CUALQUIER DAÑO INDIRECTO, ESPECIAL, INCIDENTAL O CONSIGUIENTE DE CUALQUIER TIPO, INCLUYENDO DAÑOS POR PÉRDIDA DE BENEFICIOS, PÉRDIDA DE GOBIERNO, PARADA DE TRABAJO, EXACTITUD DE LOS RESULTADOS, FALLA O FALLO DE LA INFORMÁTICA O (B) CUALQUIER CANTIDAD, EN (II) LOS MONTOS PAGADOS POR USTED PARA DESEAR EN RELACIÓN CON LOS SERVICIOS EN EL PERIODO DE DOCE (12) MESES ANTERIOR A ESTA RECLAMACIÓN APLICABLE, O (III) CUALQUIER MATERIA MÁS ALLÁ DE NUESTRO CONTROL RAZONABLE. ALGUNOS ESTADOS NO PERMITEN LA EXCLUSIÓN O LIMITACIÓN DE CIERTOS DAÑOS, POR LO QUE LA LIMITACIÓN Y EXCLUSIONES ANTERIORES PUEDEN NO APLICARSE A USTED.</p>
						<p>Indemnidad. En la mayor medida permitida por la ley aplicable, Usted acepta indemnizar y mantener a Lunettes, sus afiliados, oficiales, agentes, empleados y socios a salvo de y contra todas y cada una de las reclamaciones, responsabilidades, daños (reales y consecuentes), pérdidas y gastos Incluyendo los honorarios de los abogados) que surjan o estén relacionados de cualquier manera con cualquier reclamación de terceros relacionada con (a) su uso de los Servicios (incluyendo cualquier acción tomada por un tercero usando su cuenta) y (b) su violación de estos Términos . En el caso de una reclamación, demanda o acción ("Reclamación"), intentaremos proporcionar una notificación de la Reclamación a la información de contacto que tengamos para su cuenta (siempre y cuando el hecho de no entregar dicha notificación no elimine o reduzca su Obligaciones de indemnización que se detallan a continuación).</p>
						<p>Asignación. Usted no puede asignar, delegar ni transferir estos Términos ni sus derechos u obligaciones en virtud del presente, ni su cuenta de Servicios, de ninguna manera (por aplicación de la ley o de otro modo) sin el consentimiento previo por escrito de Lunettes. Podemos transferir, asignar o delegar estos Términos y nuestros derechos y obligaciones sin consentimiento.</p>
						<p>Diverso. Usted será responsable de pagar, retener, archivar y reportar todos los impuestos, deberes y otras evaluaciones gubernamentales asociadas con su actividad en relación con los Servicios, siempre que el Deseo pueda, a su sola discreción, hacer cualquiera de los anteriores en su En su nombre o en su propio beneficio. El hecho de que usted o nosotros no ejercitemos, de ninguna manera, ningún derecho en el presente documento no se considerará una renuncia de cualquier otro derecho en virtud del presente. Si alguna disposición de estas Condiciones se encuentra inaplicable o inválida, dicha disposición será limitada o eliminada, en la medida mínima necesaria, de manera que estos Términos permanecerán en pleno vigor y efecto y ejecutables. Usted y Lunettes acuerdan que estos Términos son la declaración completa y exclusiva del entendimiento mutuo entre usted y Lunettes, y que reemplaza y cancela todos los acuerdos, comunicaciones y demás entendimientos previos escritos y verbales relacionados con el tema de estos Términos. Por la presente usted reconoce y acepta que usted no es un empleado, agente, socio o empresa conjunta de Lunettes, y usted no tiene ninguna autoridad de ningún tipo para obligar a Lunettes en cualquier aspecto. Excepto como se indica expresamente en la sección anterior con respecto a las Aplicaciones de Apple, usted y Lunettes acuerdan que no hay beneficiarios de terceros previstos bajo estos Términos.</p>
						<p>Resolución de conflictos.</p>
						<p>Arbitraje bilateral, obligatorio y renuncia a las acciones colectivas.</p>
						<p>Por favor, lea cuidadosamente. Afecta sus derechos. USTED Y DESEO ACEPTAN QUE CUALQUIER DISPUTA, CONTROVERSIA O RECLAMO QUE SURJA DE O RELACIONADO CON SU USO DE DESEO, A CUALQUIER PRODUCTO O SERVICIO VENDIDO O DISTRIBUIDO POR ESTE ACUERDO, O AL CONTENIDO Y / O USUARIO LA SUBMISIÓN (AUDIENCIA PÚBLICA, PERSONAL Y / O LIMITADA) SE DESARROLLARÁ ÚNICAMENTE POR ARBITRAJE FINAL Y VINCULANTE, BILATERAL, excepto que usted puede presentar reclamaciones en un tribunal de reclamos menores si sus reclamaciones califican; Y este acuerdo para arbitrar no incluye el derecho de su o de Lunettes a solicitar una medida cautelar u otra reparación equitativa en un tribunal estatal o federal en México para prevenir la infracción real o amenazada, apropiación indebida o violación de los derechos de autor de una parte, , Patentes u otros derechos de propiedad intelectual.</p>
						<p>No hay juez o jurado en el arbitraje, y la revisión judicial de un laudo de arbitraje es limitada. Sin embargo, un árbitro puede conceder individualmente los mismos daños y perjuicios que un tribunal (incluyendo medidas cautelares y declaratorias o daños legales) y debe seguir los términos de estos Términos de Uso.</p>
						<p>Aviso de disputas</p>
						<p>Antes de iniciar un arbitraje, usted y Lunettes se comprometen a entregar primero al otro una notificación por escrito ("Aviso de Disputa"), que contendrá: (a) una descripción escrita del problema y los documentos pertinentes e información de apoyo; Y (b) una declaración del alivio específico buscado. Un aviso de disputa debe enviarse a: Una calle Sansome, México, CP 94104 o por correo electrónico a support@Lunettes.com. Lunettes proporcionará un aviso de disputa a usted a través de la dirección de correo electrónico asociada con su ID de usuario de Lunettes. Usted y Lunettes acuerdan intentar resolver la disputa antes de iniciar un arbitraje y no iniciar un procedimiento de arbitraje hasta que expire este período de resolución de 45 días después de la notificación. Si un acuerdo no puede ser alcanzado dentro de cuarenta y cinco (45) días de recibir la Notificación de Disputa, usted o Lunettes pueden iniciar un procedimiento de arbitraje.</p>
						<p>Proceso y procedimiento de arbitraje</p>
						<p>A menos que usted y Lunettes acuerden lo contrario por escrito, el arbitraje será administrado por los Servicios Judiciales de Arbitraje y Mediación, Inc. ("JAMS"), de conformidad con las Reglas y Procedimientos de Arbitraje Simplificado de JAMS entonces vigentes (las " ) Y modificado por este acuerdo para arbitrar, incluyendo las reglas de presentación, administración, descubrimiento y honorarios del árbitro; ser conducido por un solo árbitro neutral; Y tener lugar en el condado donde reside. En la medida en que este acuerdo de arbitraje entre en conflicto con la Política de JAMS sobre Arbitrajes de Consumidores de conformidad con las Normas Mínimas para la Imparcialidad Procesal (las "Normas Mínimas"), se aplicarán las Normas Mínimas a ese respecto.</p>
						<p>Cada uno de nosotros está de acuerdo en que cualquier procedimiento de resolución de disputas se llevará a cabo sólo en forma individual y no en una clase o acción representativa. Además, a menos que tanto usted como Lunettes acuerden expresamente lo contrario, el árbitro no podrá consolidar más de una reclamación de una persona. Si se considera que esta prohibición de arbitraje de clase, representativo o consolidado es inaplicable, entonces la totalidad de esta disposición de arbitraje será nula y sin efecto.</p>
		   <!-- Add fancyBox main JS and CSS files -->
		<script src="js/jquery.magnific-popup.js" type="text/javascript"></script>
		<link href="css/magnific-popup.css" rel="stylesheet" type="text/css">
		<script>
			$(document).ready(function() {
				$('.popup-with-zoom-anim').magnificPopup({
					type: 'inline',
					fixedContentPos: false,
					fixedBgPos: true,
					overflowY: 'auto',
					closeBtnInside: true,
					preloader: false,
					midClick: true,
					removalDelay: 300,
					mainClass: 'my-mfp-zoom-in'
			});
		});
		</script>
           </div>
		   <div class="clear"></div>	
		  </div>
	</div>	
   </div>  
@stop